version_2_with_negative: False
test:
    _target_: src.custom_datasets.llama31_dataset_custom.Llama31DatasetCustom
    split: "test"
    data_config:
        prompt: "You are given several news passages. Write a one-page summary of all news."
        question_prompt: "Now, write a one-page summary of all the news."
        question_column: "input"
        context_column: "context"
        answer_column: "answers"
        id_column: "_id"
        use_fp16: False
        dataset_name: null
        pad_to_max_length: False
        max_length: 512 # length of system prompt + question (not full sequence)
        max_answer_length: 512
        dataset_config_name: null
        train_file: null
        validation_file: null
        test_file: "data/longbench_v1/multi_news.jsonl"
        question_max_length: 64
        context_max_length: 128000 # avg context length for multi_news
        use_rag: False
