version_2_with_negative: False
test:
    _target_: src.context_compression.custom_datasets.qa_dataset.QADataset
    split: "test"
    data_config:
        prompt: "You are given a story, which can be either a novel or a movie script, and a question. Answer the question as concisely as you can, using a single phrase if possible. Do not provide any explanation."
        question_prompt: null
        question_column: "input"
        context_column: "context"
        answer_column: "answers"
        id_column: "_id"
        use_fp16: False
        dataset_name: "THUDM/LongBench"
        pad_to_max_length: False
        max_length: 2048 # this is the length of system prompt + question
        doc_stride: 512
        max_answer_length: 128 # length of answer
        dataset_config_name: "narrativeqa"
        train_file: None
        validation_file: None
        test_file: None
        question_max_length: 64 # length of question
        context_max_length: 85000 # length of context
        use_rag: False
