version_2_with_negative: False
test:
    _target_: src.context_compression.custom_datasets.llama31_dataset_custom.Llama31DatasetCustom
    split: "test"
    data_config:
        prompt: "You are given a scientific article and a question. Answer the question as concisely as you can, using a single phrase or sentence if possible. If the question cannot be answered based on the information in the article, write \"unanswerable\". If the question is a yes/no question, answer \"yes\", \"no\", or \"unanswerable\". Do not provide any explanation."
        question_prompt: null
        question_column: "input"
        context_column: "context"
        answer_column: "answers"
        id_column: "_id"
        use_fp16: False
        dataset_name: null
        pad_to_max_length: False
        max_length: 512 # length of system prompt + question (not full sequence)
        max_answer_length: 128
        dataset_config_name: null
        train_file: null
        validation_file: null
        test_file: "data/longbench/qasper.jsonl"
        question_max_length: 64
        context_max_length: 3619 # avg context length for qasper
        use_rag: False
