version_2_with_negative: False
test:
    _target_: src.context_compression.custom_datasets.qa_dataset.QADataset
    split: "test"
    data_config:
        prompt: "Please complete the code given"
        question_prompt: "What is the next line of code?"
        question_column: "input"
        context_column: "context"
        answer_column: "answers"
        id_column: "_id"
        use_fp16: False
        dataset_name: "THUDM/LongBench"
        pad_to_max_length: False
        max_length: 2048 # this is the length of system prompt + question
        doc_stride: 512
        max_answer_length: 64
        dataset_config_name: "repobench-p"
        train_file: None
        validation_file: None
        test_file: None
        question_max_length: 64
        context_max_length: 40000
        use_rag: False
