version_2_with_negative: False
test:
    _target_: src.custom_datasets.llama31_dataset_custom.Llama31DatasetCustom
    split: "test"
    data_config:
        prompt: "You are given some examples. Summarize the dialogue into a few short sentences."
        question_prompt: null
        question_column: "input"
        context_column: "context"
        answer_column: "answers"
        id_column: "_id"
        use_fp16: False
        dataset_name: null
        pad_to_max_length: False
        max_length: 512 # length of system prompt + question (not full sequence)
        max_answer_length: 128
        dataset_config_name: null
        train_file: null
        validation_file: null
        test_file: "data/longbench_v1/samsum.jsonl"
        question_max_length: 600
        context_max_length: 128000 # avg context length for samsum
        use_rag: False
